matrix:
  RUST: [stable]

pipeline:
  build:
    image: node:bullseye
    environment:
      - DEBIAN_FRONTEND=noninteractive
    commands:
      - apt-get update
      - apt-get install --no-install-recommends --yes build-essential
      - yarn install
      - yarn run tree-sitter generate
      - yarn run tree-sitter test

  test:
    image: rust
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - rustup default $RUST
      - cargo check
      - cargo test
      - cargo install tree-sitter-cli
      - tree-sitter test
